/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.flashy;
import javax.swing.JPanel;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.ui.ApplicationFrame;
import org.jfree.ui.RefineryUtilities;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import javax.swing.JFrame;
import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class Flashy_HomeGUI extends javax.swing.JFrame {
       private TimerGUI timerFrame;
       private FlashCardDisplayGUI flashcardDisplay;
       private FlashcardInput flashcardInput;
       private FlashcardEditing flashcardEditing;
    /**
     * Creates new form Flashy_HomeGUI
     */
    public Flashy_HomeGUI(String chartTitle) {
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //Create the timer frame on initialization so timer is able to run in background and progress is saved
         timerFrame = new TimerGUI(); 
         
         JFreeChart lineChart = ChartFactory.createLineChart(
         chartTitle,
         "Day","Number of Pomodoro Sessions",
         createDataset(),
         PlotOrientation.VERTICAL,
         true,true,false);
         
        initComponents();
        chartPanel.add(new ChartPanel( lineChart));
    }
    private DefaultCategoryDataset createDataset( ) {
      DefaultCategoryDataset dataset = new DefaultCategoryDataset( );
      dataset.addValue( 1 , "Pomodoro Sessions" , "Mon" );
      dataset.addValue( 5 , "Pomodoro Sessions" , "Tues" );
      dataset.addValue( 5 , "Pomodoro Sessions" ,  "Wed" );
      dataset.addValue( 8 , "Pomodoro Sessions" , "Thur" );
      dataset.addValue( 9 , "Pomodoro Sessions" , "Fri" );
      dataset.addValue( 12 , "Pomodoro Sessions" , "Sat" );
      dataset.addValue( 15 , "Pomodoro Sessions" , "Sun" );
      return dataset;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTopBar = new javax.swing.JPanel();
        lblUserGreeting = new javax.swing.JLabel();
        pnlBackground = new javax.swing.JPanel();
        lblUserMessage = new javax.swing.JLabel();
        lblMonitorProgress = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnFlashcardEdit = new javax.swing.JButton();
        btnTimer = new javax.swing.JButton();
        btnFlashcardsView = new javax.swing.JButton();
        btnFlashcardsAdd1 = new javax.swing.JButton();
        chartPanel = new javax.swing.JPanel();
        lblStreakDisplay = new javax.swing.JLabel();
        lblStreak = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        imgStreak = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(197, 231, 227));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTopBar.setBackground(new java.awt.Color(255, 102, 102));
        pnlTopBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserGreeting.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUserGreeting.setForeground(new java.awt.Color(255, 255, 255));
        lblUserGreeting.setText("HAVE AN INSIGHT AT YOUR DASHBOARD ! ");
        pnlTopBar.add(lblUserGreeting, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 270, 20));

        getContentPane().add(pnlTopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 40));

        pnlBackground.setBackground(new java.awt.Color(204, 204, 255));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserMessage.setFont(new java.awt.Font("Trebuchet MS", 3, 15)); // NOI18N
        lblUserMessage.setForeground(new java.awt.Color(0, 0, 255));
        lblUserMessage.setText("Welcome to the FLASHY! Together, we'll turn your study sessions into epic quests toward excellence. Happy studying!\"");
        pnlBackground.add(lblUserMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 890, 60));

        lblMonitorProgress.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        lblMonitorProgress.setForeground(new java.awt.Color(255, 102, 102));
        lblMonitorProgress.setText("MONITOR YOUR PROGRESS : ");
        pnlBackground.add(lblMonitorProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 240, 30));

        pnlMenu.setBackground(new java.awt.Color(51, 51, 51));
        pnlMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHome.setBackground(new java.awt.Color(153, 153, 153));
        pnlHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        pnlHome.setForeground(new java.awt.Color(153, 153, 153));
        pnlHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setBackground(new java.awt.Color(153, 153, 153));
        btnHome.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_125694.png"))); // NOI18N
        btnHome.setText("HOME");
        pnlHome.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 40));

        pnlMenu.add(pnlHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 170, 40));

        btnFlashcardEdit.setBackground(new java.awt.Color(153, 153, 153));
        btnFlashcardEdit.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnFlashcardEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnFlashcardEdit.setText("EDIT FLASHCARDS");
        btnFlashcardEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlashcardEditActionPerformed(evt);
            }
        });
        pnlMenu.add(btnFlashcardEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 190, 40));

        btnTimer.setBackground(new java.awt.Color(153, 153, 153));
        btnTimer.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnTimer.setForeground(new java.awt.Color(255, 255, 255));
        btnTimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_timer-icon-in-hand-hand-points-at-stopwatch-timer-start-concept-illustration-free-vector.jpg"))); // NOI18N
        btnTimer.setText("TIMER");
        btnTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimerActionPerformed(evt);
            }
        });
        pnlMenu.add(btnTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 180, 40));

        btnFlashcardsView.setBackground(new java.awt.Color(153, 153, 153));
        btnFlashcardsView.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnFlashcardsView.setForeground(new java.awt.Color(255, 255, 255));
        btnFlashcardsView.setText("FLASHCARDS");
        btnFlashcardsView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlashcardsViewActionPerformed(evt);
            }
        });
        pnlMenu.add(btnFlashcardsView, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 190, 40));

        btnFlashcardsAdd1.setBackground(new java.awt.Color(153, 153, 153));
        btnFlashcardsAdd1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnFlashcardsAdd1.setForeground(new java.awt.Color(255, 255, 255));
        btnFlashcardsAdd1.setText("ADD FLASHCARDS");
        btnFlashcardsAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlashcardsAdd1ActionPerformed(evt);
            }
        });
        pnlMenu.add(btnFlashcardsAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 190, 40));

        pnlBackground.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 190, 690));

        chartPanel.setLayout(new java.awt.BorderLayout());
        pnlBackground.add(chartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 770, 420));

        lblStreakDisplay.setBackground(new java.awt.Color(255, 204, 204));
        lblStreakDisplay.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblStreakDisplay.setForeground(new java.awt.Color(255, 51, 51));
        lblStreakDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStreakDisplay.setText("7");
        lblStreakDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        pnlBackground.add(lblStreakDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 170, 60, 50));

        lblStreak.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblStreak.setForeground(new java.awt.Color(255, 102, 102));
        lblStreak.setText("YOUR STREAK :");
        pnlBackground.add(lblStreak, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 130, 50));

        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_flashy_1.png"))); // NOI18N
        lblTitle.setText("jLabel2");
        pnlBackground.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 320, 70));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grad.png"))); // NOI18N
        imgLogo.setText("jLabel5");
        pnlBackground.add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 120, 70));

        imgStreak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_1calendar5662.jpg"))); // NOI18N
        imgStreak.setText("jLabel4");
        pnlBackground.add(imgStreak, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 50, 70));

        getContentPane().add(pnlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, 1280, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimerActionPerformed
        // TODO add your handling code here:
     
    
    // Set the frame to be visible
    timerFrame.setVisible(true); //Set the timer frame to visible
        
    }//GEN-LAST:event_btnTimerActionPerformed

    private void btnFlashcardEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlashcardEditActionPerformed
        // TODO add your handling code here:
         flashcardEditing = new FlashcardEditing(); //Open the frame that allows user to edit the content of flashcards (questions and answers)
         flashcardEditing.setVisible(true);
        
         
    }//GEN-LAST:event_btnFlashcardEditActionPerformed

    private void btnFlashcardsViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlashcardsViewActionPerformed
        // TODO add your handling code here:
        flashcardDisplay = new FlashCardDisplayGUI(); //Open the frame to view all flashcards the user has created.
        flashcardDisplay.setVisible(true);
    }//GEN-LAST:event_btnFlashcardsViewActionPerformed

    private void btnFlashcardsAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlashcardsAdd1ActionPerformed
        // TODO add your handling code here:
        flashcardInput = new FlashcardInput(); //Open the frame to add flashcards
          flashcardInput.setVisible(true);
    }//GEN-LAST:event_btnFlashcardsAdd1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flashy_HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flashy_HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flashy_HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flashy_HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Flashy_HomeGUI(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFlashcardEdit;
    private javax.swing.JButton btnFlashcardsAdd1;
    private javax.swing.JButton btnFlashcardsView;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnTimer;
    private javax.swing.JPanel chartPanel;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel imgStreak;
    private javax.swing.JLabel lblMonitorProgress;
    private javax.swing.JLabel lblStreak;
    private javax.swing.JLabel lblStreakDisplay;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserGreeting;
    private javax.swing.JLabel lblUserMessage;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlTopBar;
    // End of variables declaration//GEN-END:variables
}
