/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.flashy;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author arpan
 */
public class FlashcardInput extends javax.swing.JFrame {
    private JComboBox<String> categoryComboBox;
    /**
     * Creates new form FlashcardInput
     */
    public FlashcardInput() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAnswer = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtTopic = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Question");

        jLabel2.setText("Answer");

        txtAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnswerActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Topic");

        txtTopic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTopicActionPerformed(evt);
            }
        });

        jButton1.setText("Add Category");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove Category");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAdd)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(109, 109, 109)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemove)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnswerActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
       String category = (String) jComboBox1.getSelectedItem();
        String topic = txtTopic.getText();
        String question = jTextArea1.getText();
        String answer = txtAnswer.getText();

        ArrayList<String> errors = new ArrayList<>();

        if (category == null || category.trim().isEmpty()) {
            errors.add("Category is missing.");
        }

        if (topic == null || topic.trim().isEmpty()) {
            errors.add("Topic is missing.");
        }

        if (question == null || question.trim().isEmpty()) {
            errors.add("Question is missing.");
        }

        if (answer == null || answer.trim().isEmpty()) {
            errors.add("Answer is missing.");
        }

        if (!errors.isEmpty()) {
            // Print error messages for missing inputs
            String errorMessage = "Errors:\n";
            for (String error : errors) {
                errorMessage += error + "\n";
            }
            JOptionPane.showMessageDialog(this, errorMessage, "Input Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Flashcard flashcard = new Flashcard(category, topic, question, answer);
            saveFlashcardToJson(flashcard);
        }
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtTopicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTopicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTopicActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String category = JOptionPane.showInputDialog(this, "Enter a category:");

    // Check if the user entered a category and it's not empty
    if (category != null && !category.trim().isEmpty()) {
        // Add the category to the jComboBox1
        DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) jComboBox1.getModel();
        model.addElement(category);
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        JFrame categoryFrame = new JFrame("Categories");
    
    // Create a JList to display the categories
    DefaultListModel<String> listModel = new DefaultListModel<>();
    for (int i = 0; i < jComboBox1.getItemCount(); i++) {
        listModel.addElement(jComboBox1.getItemAt(i).toString());
    }
    JList<String> categoryList = new JList<>(listModel);
    JScrollPane scrollPane = new JScrollPane(categoryList);

    // Create a button to remove the selected category
    JButton removeButton = new JButton("Remove");
    removeButton.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            String selectedCategory = categoryList.getSelectedValue();
            if (selectedCategory != null) {
                // Delete the corresponding folder
                deleteCategoryFolder(selectedCategory);
                
                // Remove the selected item from jComboBox1
                jComboBox1.removeItem(selectedCategory);
                
                categoryFrame.dispose(); // Close the category frame
            }
        }
    });

    // Create a panel to hold the components using GridBagLayout
    JPanel panel = new JPanel(new GridBagLayout());
    GridBagConstraints gbc = new GridBagConstraints();
    gbc.insets = new Insets(10, 10, 10, 10); // Add some padding
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    gbc.fill = GridBagConstraints.BOTH;
    
    // Add the scroll pane to the panel
    panel.add(scrollPane, gbc);

    // Increment the y-coordinate for the remove button
    gbc.gridy++;
    gbc.weighty = 0.0;
    
    // Add the remove button to the panel
    panel.add(removeButton, gbc);

    // Add the panel to the frame
    categoryFrame.add(panel);

    // Set the default close operation to dispose on close
    categoryFrame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

    // Pack and set the frame to be visible
    categoryFrame.pack();
    categoryFrame.setVisible(true);

    }//GEN-LAST:event_btnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlashcardInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlashcardInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlashcardInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlashcardInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlashcardInput().setVisible(true);
            }
        });
    } private static void saveFlashcardToJson(Flashcard flashcard) {
    try {
        // Create a directory for the category and topic if they don't exist
        String rootDirectory = "Flashcards";
        String categoryDirectory = rootDirectory + "/" + flashcard.getFlashCardCategory();
        String topicDirectory = categoryDirectory + "/" + flashcard.getTopic();

        File root = new File(rootDirectory);
        File categoryDir = new File(categoryDirectory);
        File topicDir = new File(topicDirectory);

        if (!root.exists()) {
            root.mkdir();
        }
        
        if (!categoryDir.exists()) {
            categoryDir.mkdir();
        }

        if (!topicDir.exists()) {
            topicDir.mkdir();
        }

        // Create a JSON file with the flashcard details
        String filePath = topicDirectory + "/flashcards.json";
        File file = new File(filePath);

        // Create JSON data manually without newlines for compact formatting
        String jsonData = "{" +
                "\"question\": \"" + flashcard.getQuestion().replace("\"", "\\\"") + "\"," +
                "\"answer\": \"" + flashcard.getAnswer().replace("\"", "\\\"") + "\"" +
                "}";

        // If the JSON file already exists, append the new flashcard data
        if (file.exists()) {
            BufferedReader reader = new BufferedReader(new FileReader(file));
            StringBuilder existingJsonData = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                existingJsonData.append(line);
            }
            reader.close();

            // Remove trailing square bracket and add a comma
            String existingJsonStr = existingJsonData.toString();
            existingJsonStr = existingJsonStr.substring(0, existingJsonStr.length() - 1);
            existingJsonStr += ",";

            // Append the new flashcard data
            BufferedWriter writer = new BufferedWriter(new FileWriter(file));
            writer.write(existingJsonStr + jsonData + "]");
            writer.close();
        } else {
            // If the file doesn't exist, create a new JSON file with compact formatting
            BufferedWriter writer = new BufferedWriter(new FileWriter(file));
            writer.write("[" + jsonData + "]");
            writer.close();
        }

        System.out.println("Flashcard saved to: " + filePath);
    } catch (IOException e) {
        e.printStackTrace();
    }
} private void deleteCategoryFolder(String category) {
    // Define the path to the folder to be deleted
    String folderPath = "Flashy\\Flashcards\\" + category;
    File folderToDelete = new File(folderPath);

    // Check if the folder exists and delete it
    if (folderToDelete.exists() && folderToDelete.isDirectory()) {
        String[] entries = folderToDelete.list();
        for (String entry : entries) {
            File currentFile = new File(folderToDelete.getPath(), entry);
            currentFile.delete();
        }
        folderToDelete.delete();
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JTextField txtTopic;
    // End of variables declaration//GEN-END:variables
}
